// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBNWdNS_-Lb_69u8hWG7RvKOJ45VzlHyps',
//     appId: '1:566550439636:web:8f6856f00db4b218ac3d41',
//     messagingSenderId: '566550439636',
//     projectId: 'adevnutralb',
//     authDomain: 'adevnutralb.firebaseapp.com',
//     storageBucket: 'adevnutralb.firebasestorage.app',
//     measurementId: 'G-4324CP5PBS',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBm-MD0JvMFZkRSB2-5SByzm2ZrxkuwlQc',
//     appId: '1:566550439636:android:312885af4748dcacac3d41',
//     messagingSenderId: '566550439636',
//     projectId: 'adevnutralb',
//     storageBucket: 'adevnutralb.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBcoLtV33EX9GDJq0GBynJCgrg6tEX61aw',
//     appId: '1:566550439636:ios:a6835745534b7aa2ac3d41',
//     messagingSenderId: '566550439636',
//     projectId: 'adevnutralb',
//     storageBucket: 'adevnutralb.firebasestorage.app',
//     iosBundleId: 'com.example.adventura',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBcoLtV33EX9GDJq0GBynJCgrg6tEX61aw',
//     appId: '1:566550439636:ios:a6835745534b7aa2ac3d41',
//     messagingSenderId: '566550439636',
//     projectId: 'adevnutralb',
//     storageBucket: 'adevnutralb.firebasestorage.app',
//     iosBundleId: 'com.example.adventura',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBNWdNS_-Lb_69u8hWG7RvKOJ45VzlHyps',
//     appId: '1:566550439636:web:888fc6486dd8e6e7ac3d41',
//     messagingSenderId: '566550439636',
//     projectId: 'adevnutralb',
//     authDomain: 'adevnutralb.firebaseapp.com',
//     storageBucket: 'adevnutralb.firebasestorage.app',
//     measurementId: 'G-FLR6JDS288',
//   );
// }
